### PR TITLE
Improve website structure and style

### PR DESCRIPTION
**Pull request by camchenry**
This is a WIP pull request. Do not merge.

I hope these changes are not too trivial to consider. I wanted to work on adding some structure to the site, in anticipation to potentially adding more data and links to things (#21, #22, #48, #19, #26, etc.). I would welcome suggestions/issues that you have and would like me to address.

Before:
image

After:
image
(screenshots taken in Firefox 61, Ubuntu 17.10)

### CODE REVIEW

**Comment by anp** [comment]
This looks great! Excited to see what else you're working on :).

**Comment by camchenry** [comment]
Just curious, what are your thoughts on using a framework for this? I'm not opposed either way. So far, I have just been using vanilla CSS to put something together, which has the name benefit of everything being very lightweight (<70KB). However, a framework could be more consistent and easier for others to learn.

**Comment by anp** [comment]
@camchenry this is looking really awesome :D. Would you mind rebasing your branch onto master so that the latest CI changes can run? I'd selfishly like to test the screenshotting I added and hopefully I can get the automated deployment working in time for when this is ready to merge.

**Comment by camchenry** [comment]
Yeah I'll update the branch when I get a chance.

On Oct 14, 2018 7:47 PM, "Adam Perry" <notifications@github.com> wrote:

@camchenry <https://github.com/camchenry> this is looking really awesome
:D. Would you mind rebasing your branch onto master so that the latest CI
changes can run? I'd selfishly like to test the screenshotting I added and
hopefully I can get the automated deployment working in time for when this
is ready to merge.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/anp/lolbench/pull/55#issuecomment-429673691>, or mute
the thread

**Comment by camchenry** [comment]
Been a while since I rebased, hopefully that looks okay. I suppose you can just squash this pull request later.

**Comment by anp** [comment]
Thank you so much! I squashed the commits down but kept your messages. Should be live on the site in an hour or two.

**Pull request merged**
